#!/usr/bin/perl -T

# parse out /srv/*/apps/list into systemd services
# runs under -T even though it is not strictly setuid to provide an extra layer of paranoia protection

use strict;
use warnings;

open(STDOUT, ">>/dev/kmsg") || die "h-a-g: STDOUT: Cannot redirect to /dev/kmsg: $!";
open(STDERR, ">>/dev/kmsg") || die "h-a-g: STDERR: Cannot redirect to /dev/kmsg: $!";

use Data::Dumper;
print Dumper(\@ARGV);

use File::Path qw(make_path);

my $target_dir = $ARGV[0] || '/tmp';
$target_dir =~ /^(.*)$/;
$target_dir = $1;

make_path($target_dir) or die "h-a-g: Failed to make $target_dir: $!";

while (glob('/srv/*/apps/list')) {
        my $list_file = $_;
        open LIST, "<$list_file" or next;
        while (<LIST>) {
                chomp;
                next if /^#/;
                next unless /^([^;]*);([^;]*);([^;]*)$/;
                my ($type, $name, $location) = ($1, $2, $3);
                print "h-a-g: Will configure a $type container for $location in $name (from $list_file)\n";
        }
        close LIST;
}
