#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

# avoid having a mess
# see https://projects.puppetlabs.com/issues/20913
gem uninstall puppet

if [ ! -x /usr/sbin/puppetd ] ; then

	aptitude update
	aptitude -y full-upgrade
	aptitude -y install puppet # replace the gem-installed version available in the box

fi

puppet resource host "$2" ip="$1"

